// Shared data model for both directions

const COMBATANTS = [
  {
    id: "lyra",
    name: "Lyra Vex",
    kind: "pc",
    pcClass: "Rogue 7 · Elf",
    init: 24,
    hp: 78, maxHp: 92, tempHp: 4,
    ac: 25,
    perception: "+15",
    speeds: "30 ft",
    saves: { fort: "+11", ref: "+17", will: "+13" },
    skills: "Acrobatics +17, Stealth +19, Thievery +17, Society +13",
    immunities: [],
    resistances: [],
    weaknesses: [],
    conditions: [
      { name: "Frightened", value: 1, duration: "End of next turn" },
    ],
    persistent: [],
    strikes: [
      { name: "Rapier", bonus: "+17", dmg: "1d6+5 P + 2d6 sneak", traits: "agile, deadly d8, finesse" },
      { name: "Shortbow", bonus: "+17", dmg: "1d6+2 P + 2d6 sneak", traits: "deadly d10, range 60 ft" },
    ],
    spellSlots: null,
    notes: "Hidden behind pillar — observed by goblin scout?",
  },
  {
    id: "kael",
    name: "Kael Ironhand",
    kind: "pc",
    pcClass: "Champion 7 · Dwarf",
    init: 19,
    hp: 96, maxHp: 112, tempHp: 0,
    ac: 28,
    perception: "+13",
    speeds: "20 ft",
    saves: { fort: "+17", ref: "+11", will: "+15" },
    skills: "Athletics +17, Religion +13, Diplomacy +13",
    immunities: [],
    resistances: [{ type: "fire", value: 5 }],
    weaknesses: [],
    conditions: [],
    persistent: [],
    strikes: [
      { name: "Warhammer +1", bonus: "+19", dmg: "1d8+7 B", traits: "shove" },
      { name: "Steel Shield", bonus: "+17", dmg: "1d4+5 B", traits: "—" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "skitter",
    name: "Goblin Pyro",
    kind: "enemy",
    creatureType: "Goblin · Lvl 3",
    init: 22,
    hp: 18, maxHp: 38, tempHp: 0,
    ac: 19,
    perception: "+9",
    speeds: "25 ft",
    saves: { fort: "+7", ref: "+11", will: "+8" },
    skills: "Acrobatics +11, Stealth +11, Crafting (alchemy) +9",
    immunities: [],
    resistances: [{ type: "fire", value: 5 }],
    weaknesses: [{ type: "cold iron", value: 5 }],
    conditions: [
      { name: "Off-Guard", value: null, duration: "1 round" },
    ],
    persistent: [
      { type: "bleed", value: "1d6" },
    ],
    strikes: [
      { name: "Alchemist's Fire", bonus: "+12", dmg: "2d8 fire + 1 splash", traits: "thrown 20 ft, splash" },
      { name: "Dogslicer", bonus: "+11", dmg: "1d6+3 S", traits: "agile, backstabber, finesse" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "morak",
    name: "Cult Brute",
    kind: "enemy",
    creatureType: "Human Cultist · Lvl 5",
    init: 17,
    hp: 64, maxHp: 75, tempHp: 0,
    ac: 22,
    perception: "+11",
    speeds: "25 ft",
    saves: { fort: "+13", ref: "+9", will: "+11" },
    skills: "Athletics +13, Intimidation +11, Religion +9",
    immunities: [],
    resistances: [],
    weaknesses: [],
    conditions: [
      { name: "Stunned", value: 1, duration: "—" },
    ],
    persistent: [],
    strikes: [
      { name: "Greataxe", bonus: "+15", dmg: "1d12+7 S", traits: "sweep" },
      { name: "Heavy Crossbow", bonus: "+12", dmg: "1d10+2 P", traits: "range 120 ft, reload 2" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "willowmae",
    name: "Willow Mae",
    kind: "pc",
    pcClass: "Wizard 7 · Halfling",
    init: 14,
    hp: 52, maxHp: 64, tempHp: 6,
    ac: 23,
    perception: "+13",
    speeds: "25 ft",
    saves: { fort: "+11", ref: "+13", will: "+17" },
    skills: "Arcana +17, Crafting +15, Society +15, Occultism +15",
    immunities: [],
    resistances: [],
    weaknesses: [],
    conditions: [
      { name: "Concentrating", value: null, duration: "Sustained: Mirror Image" },
    ],
    persistent: [],
    strikes: [
      { name: "Staff +1", bonus: "+12", dmg: "1d4+1 B", traits: "two-hand d8" },
    ],
    spellSlots: {
      4: { used: 1, max: 3, prepared: ["Fly", "Fireball", "Wall of Fire"] },
      3: { used: 0, max: 3, prepared: ["Haste", "Slow", "Lightning Bolt"] },
      2: { used: 2, max: 3, prepared: ["Mirror Image", "Invisibility", "Glitterdust"] },
      1: { used: 1, max: 3, prepared: ["Magic Missile", "Grease", "Shield"] },
    },
    notes: "Concentrating on Mirror Image — 2 images remaining",
  },
  {
    id: "brann",
    name: "Brann Stout",
    kind: "pc",
    pcClass: "Ranger 7 · Human",
    init: 16,
    hp: 84, maxHp: 88, tempHp: 0,
    ac: 24,
    perception: "+17",
    speeds: "30 ft",
    saves: { fort: "+15", ref: "+15", will: "+11" },
    skills: "Survival +17, Athletics +13, Nature +13, Stealth +15",
    immunities: [], resistances: [], weaknesses: [],
    conditions: [],
    persistent: [],
    strikes: [
      { name: "Composite Longbow +1", bonus: "+17", dmg: "1d8+5 P", traits: "deadly d10, range 100 ft" },
      { name: "Hatchet", bonus: "+15", dmg: "1d6+5 S", traits: "agile, sweep" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "acolyte1",
    name: "Cult Acolyte",
    kind: "enemy",
    creatureType: "Human Cultist · Lvl 3",
    init: 15,
    hp: 42, maxHp: 50, tempHp: 0,
    ac: 19,
    perception: "+9",
    speeds: "25 ft",
    saves: { fort: "+9", ref: "+7", will: "+11" },
    skills: "Religion +11, Stealth +9",
    immunities: [], resistances: [], weaknesses: [],
    conditions: [],
    persistent: [],
    strikes: [
      { name: "Dagger", bonus: "+11", dmg: "1d4+3 P", traits: "agile, finesse" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "acolyte2",
    name: "Cult Acolyte",
    kind: "enemy",
    creatureType: "Human Cultist · Lvl 3",
    init: 13,
    hp: 28, maxHp: 50, tempHp: 0,
    ac: 19,
    perception: "+9",
    speeds: "25 ft",
    saves: { fort: "+9", ref: "+7", will: "+11" },
    skills: "Religion +11, Stealth +9",
    immunities: [], resistances: [], weaknesses: [],
    conditions: [{ name: "Frightened", value: 2, duration: "End of turn" }],
    persistent: [],
    strikes: [
      { name: "Dagger", bonus: "+11", dmg: "1d4+3 P", traits: "agile, finesse" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "shadow",
    name: "Shadow",
    kind: "enemy",
    creatureType: "Incorporeal Undead · Lvl 4",
    init: 13,
    hp: 50, maxHp: 50, tempHp: 0,
    ac: 21,
    perception: "+11",
    speeds: "Fly 25 ft",
    saves: { fort: "+7", ref: "+13", will: "+11" },
    skills: "Stealth +13, Acrobatics +11",
    immunities: ["disease", "death effects", "paralyzed"],
    resistances: [{ type: "all", value: 5 }],
    weaknesses: [],
    conditions: [],
    persistent: [],
    strikes: [
      { name: "Shadow Hand", bonus: "+14", dmg: "2d8+2 negative", traits: "agile, finesse, magical" },
    ],
    spellSlots: null,
    notes: "",
  },
  {
    id: "highpriest",
    name: "High Priest Vorn",
    kind: "enemy",
    creatureType: "Human Cleric · Lvl 6",
    init: 12,
    hp: 88, maxHp: 88, tempHp: 0,
    ac: 24,
    perception: "+14",
    speeds: "20 ft",
    saves: { fort: "+13", ref: "+11", will: "+16" },
    skills: "Religion +16, Intimidation +14, Occultism +12",
    immunities: [],
    resistances: [],
    weaknesses: [{ type: "good", value: 5 }],
    conditions: [],
    persistent: [],
    strikes: [
      { name: "Mace +1", bonus: "+16", dmg: "1d6+6 B", traits: "shove" },
    ],
    spellSlots: {
      3: { used: 0, max: 3, prepared: ["Harm", "Bind Undead", "Vampiric Touch"] },
      2: { used: 1, max: 3, prepared: ["Harm", "Silence", "Spiritual Weapon"] },
      1: { used: 0, max: 3, prepared: ["Harm", "Bane", "Fear"] },
    },
    notes: "",
  },
];

const BESTIARY = [
  { name: "Goblin Warrior", lvl: -1, traits: ["goblin", "humanoid"] },
  { name: "Goblin Pyro", lvl: 3, traits: ["goblin", "humanoid"] },
  { name: "Hobgoblin Soldier", lvl: 1, traits: ["hobgoblin", "humanoid"] },
  { name: "Bugbear Marauder", lvl: 4, traits: ["goblin", "humanoid"] },
  { name: "Cult Brute", lvl: 5, traits: ["human", "humanoid"] },
  { name: "Cult Acolyte", lvl: 3, traits: ["human", "humanoid"] },
  { name: "High Priest Vorn", lvl: 6, traits: ["human", "humanoid", "boss"] },
  { name: "Animated Statue", lvl: 4, traits: ["construct", "mindless"] },
  { name: "Shadow", lvl: 4, traits: ["incorporeal", "undead"] },
  { name: "Giant Spider", lvl: 1, traits: ["animal"] },
  { name: "Owlbear", lvl: 4, traits: ["beast"] },
  { name: "Drake, Forest", lvl: 5, traits: ["dragon"] },
];

const PARTY = [
  { name: "Lyra Vex", pcClass: "Rogue 7 · Elf" },
  { name: "Kael Ironhand", pcClass: "Champion 7 · Dwarf" },
  { name: "Willow Mae", pcClass: "Wizard 7 · Halfling" },
  { name: "Brann Stout", pcClass: "Ranger 7 · Human" },
];

// PF2e condition reference (short text from public PF2e SRD-style summaries — paraphrased)
const CONDITIONS_REF = {
  "Off-Guard": { value: false, text: "−2 circumstance penalty to AC. Flanked, surprised, or unaware." },
  "Frightened": { value: true, text: "Status penalty to checks/DCs equal to value. Decreases by 1 at end of turn." },
  "Stunned": { value: true, text: "Lose actions equal to value (or all on duration). Cannot act this turn." },
  "Slowed": { value: true, text: "Lose this many actions at the start of each turn." },
  "Sickened": { value: true, text: "Status penalty to checks/DCs. Cannot willingly drink or eat." },
  "Wounded": { value: true, text: "When dying, increase dying value by wounded value + 1." },
  "Dying": { value: true, text: "At 4, dead. Recovery check at start of turn." },
  "Prone": { value: false, text: "−2 to attacks. Off-guard. Stand = single action." },
  "Concentrating": { value: false, text: "Sustaining a spell or action this turn." },
  "Quickened": { value: false, text: "Gain an extra action each turn (specific use)." },
  "Persistent: Bleed": { value: true, text: "Take damage at end of turn. DC 15 flat to end." },
  "Persistent: Fire": { value: true, text: "Take damage at end of turn. DC 15 flat to end." },
};

const COMBAT_LOG = [
  { round: 3, actor: "Lyra Vex", text: "Strike (Rapier) vs Goblin Pyro: hit AC 19 → 11 damage", kind: "hit" },
  { round: 3, actor: "Lyra Vex", text: "Sneak Attack: +2d6 → 8 precision damage", kind: "hit" },
  { round: 3, actor: "Goblin Pyro", text: "becomes Off-Guard (flanked)", kind: "condition" },
  { round: 3, actor: "Kael Ironhand", text: "Raise Shield · +2 circumstance to AC", kind: "action" },
  { round: 3, actor: "Kael Ironhand", text: "Strike (Warhammer +1) vs Cult Brute: crit AC 22 → 22 damage", kind: "crit" },
  { round: 3, actor: "Cult Brute", text: "becomes Stunned 1", kind: "condition" },
  { round: 2, actor: "Willow Mae", text: "casts Fireball (4th rank) — 11d6 fire (38)", kind: "spell" },
  { round: 2, actor: "Goblin Pyro", text: "Reflex save: 14 → fail · 38 fire", kind: "miss" },
  { round: 2, actor: "Cult Brute", text: "Reflex save: 21 → success · 19 fire", kind: "hit" },
  { round: 2, actor: "Willow Mae", text: "Sustain Mirror Image (2 images)", kind: "action" },
  { round: 1, actor: "Initiative", text: "Round 1 begins · Lyra 24, Goblin 22, Kael 19, Brute 17, Willow 14, Vorn 12", kind: "system" },
];

window.PF2E_DATA = { COMBATANTS, BESTIARY, PARTY, CONDITIONS_REF, COMBAT_LOG };
